[package]
name = "wordle"
version = "1.0.0"
authors = ["Samuel Corsi-House <chouse.samuel@gmail.com>"]
edition = "2021"

[dependencies]
crossterm = "0.26.1"
dialoguer = "0.10.4"
paris = { version = "1.5.15", features = ["macros", "no_logger"] }
